# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_mailbox', '0006_mailbox_last_polling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'E-mail message', 'verbose_name_plural': 'E-mail messages'},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'verbose_name': 'Message attachment', 'verbose_name_plural': 'Message attachments'},
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, help_text='When applicable indicates the User sender of the email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='From user'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_dsn',
            field=models.BooleanField(default=False, verbose_name='Is DSN'),
        ),
        migrations.AddField(
            model_name='message',
            name='parsed',
            field=models.BooleanField(default=False, verbose_name='Parsed'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='from_email',
            field=models.CharField(blank=True, default='', help_text="Example: MailBot &lt;mailbot@yourdomain.com&gt;<br />'From' header to set for outgoing email.<br /><br />If you do not use this e-mail inbox for outgoing mail, this setting is unnecessary.<br />If you send e-mail without setting this, your 'From' header will'be set to match the setting `DEFAULT_FROM_EMAIL`.", max_length=255, verbose_name='From email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='uri',
            field=models.CharField(blank=True, default='', help_text="Example: imap+ssl://myusername:mypassword@someserver <br /><br />Internet transports include 'imap' and 'pop3'; common local file transports include 'maildir', 'mbox', and less commonly 'babyl', 'mh', and 'mmdf'. <br /><br />Be sure to urlencode your username and password should they contain illegal characters (like @, :, etc).", max_length=255, verbose_name='URI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read'),
        ),
    ]
